'use client'

export async function exportMessageToPdf(content: string): Promise<void> {
  const { default: jsPDF } = await import('jspdf')

  const now = new Date()
  const timestamp = now.toISOString().replace(/[-:T]/g, '').slice(0, 15)
  const filename = `devbrain-ai-${timestamp}.pdf`

  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const margin = 15
  const maxWidth = pageWidth - margin * 2

  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.text('DevBrain AI', margin, 20)

  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(120, 120, 120)
  doc.text(`Generated: ${now.toLocaleString()}`, margin, 27)

  doc.setDrawColor(150, 100, 220)
  doc.line(margin, 30, pageWidth - margin, 30)

  doc.setFontSize(11)
  doc.setTextColor(30, 30, 30)
  const lines = doc.splitTextToSize(content, maxWidth)
  doc.text(lines, margin, 38)

  doc.setFontSize(9)
  doc.setTextColor(150)
  doc.text('Generated by DevBrain · devbrain.app', margin, pageHeight - 10)

  doc.save(filename)
}
